#!/usr/bin/env bash
# Run a command inside the container with ROS 2 Humble and this workspace sourced.
exec docker exec -i -w /home/ros/ros2_ws/src/martha_nav ros2_humble \
  bash -lc 'source /opt/ros/humble/setup.bash
            [ -f /home/ros/ros2_ws/install/setup.bash ] && source /home/ros/ros2_ws/install/setup.bash
            exec "$@"' _ "$@"
